Creation of Workforce Insights Dashboard for Employee Skill and Analytics

## Data Cleaning and Preprocessing

### Objective

This notebook prepares the raw workforce dataset for downstream analytics and machine learning.

The preprocessing workflow includes:
- Data quality validation
- Identification of non-informative attributes
- Data type validation
- Categorical value standardization
- Feature engineering
- Target variable preparation
- Final dataset validation
- Export of the processed dataset

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
df = pd.read_csv(
    "../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv"
)

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [3]:
df_clean = df.copy()

In [4]:
duplicate_count = df_clean.duplicated().sum()

print("Duplicate records:", duplicate_count)

Duplicate records: 0

In [5]:
if duplicate_count > 0:
    df_clean = df_clean.drop_duplicates()

In [6]:
missing_values = df_clean.isnull().sum()

missing_values[missing_values > 0]

Series([], dtype: int64)

In [7]:
constant_columns = [
    column for column in df_clean.columns
    if df_clean[column].nunique() <= 1
]

constant_columns

['EmployeeCount', 'Over18', 'StandardHours']

In [8]:
for column in constant_columns:
    print(column)
    print(df_clean[column].unique())
    print()

EmployeeCount
[1]

Over18
['Y']

StandardHours
[80]

In [9]:
df_clean = df_clean.drop(columns=constant_columns)

In [10]:
df_clean["EmployeeNumber"].nunique()

1470

In [11]:
len(df_clean)

1470

In [12]:
df_clean = df_clean.rename(
    columns={"EmployeeNumber": "EmployeeID"}
)

In [13]:
df_clean.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeID,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Yes,11,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,No,23,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Yes,15,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Yes,11,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,No,12,3,4,1,6,3,3,2,2,2,2

In [14]:
categorical_columns = df_clean.select_dtypes(
    include="object"
).columns

categorical_columns

Index(['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender',
       'JobRole', 'MaritalStatus', 'OverTime'],
      dtype='object')

In [15]:
for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(df_clean[column].value_counts())

--- Attrition ---
Attrition
No     1233
Yes     237
Name: count, dtype: int64

--- BusinessTravel ---
BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

--- Department ---
Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

--- EducationField ---
EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

--- Gender ---
Gender
Male      882
Female    588
Name: count, dtype: int64

--- JobRole ---
JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

--- MaritalStatus ---
MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

--- OverTime ---
OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [16]:
df_clean["AttritionFlag"] = (
    df_clean["Attrition"]
    .map({"No": 0, "Yes": 1})
)

In [17]:
df_clean[["Attrition", "AttritionFlag"]].head(10)

  Attrition  AttritionFlag
0       Yes              1
1        No              0
2       Yes              1
3        No              0
4        No              0
5        No              0
6        No              0
7        No              0
8        No              0
9        No              0

In [18]:
df_clean["AttritionFlag"].value_counts()

AttritionFlag
0    1233
1     237
Name: count, dtype: int64

In [19]:
df_clean["TenureGroup"] = pd.cut(
    df_clean["YearsAtCompany"],
    bins=[-1, 2, 5, 10, np.inf],
    labels=[
        "0-2 Years",
        "3-5 Years",
        "6-10 Years",
        "10+ Years"
    ]
)

In [20]:
df_clean["TenureGroup"].value_counts()

TenureGroup
6-10 Years    448
3-5 Years     434
0-2 Years     342
10+ Years     246
Name: count, dtype: int64

In [21]:
df_clean["AgeGroup"] = pd.cut(
    df_clean["Age"],
    bins=[0, 25, 35, 45, 55, np.inf],
    labels=[
        "Under 25",
        "25-35",
        "36-45",
        "46-55",
        "56+"
    ]
)

In [22]:
df_clean["AgeGroup"].value_counts()

AgeGroup
25-35       606
36-45       468
46-55       226
Under 25    123
56+          47
Name: count, dtype: int64

In [23]:
df_clean["YearsSincePromotionRatio"] = (
    df_clean["YearsSinceLastPromotion"]
    / df_clean["YearsAtCompany"].replace(0, np.nan)
)

In [24]:
df_clean["YearsSincePromotionRatio"] = (
    df_clean["YearsSincePromotionRatio"].fillna(0)
)

In [25]:
df_clean["ExperienceGroup"] = pd.cut(
    df_clean["TotalWorkingYears"],
    bins=[-1, 2, 5, 10, 20, np.inf],
    labels=[
        "0-2 Years",
        "3-5 Years",
        "6-10 Years",
        "11-20 Years",
        "20+ Years"
    ]
)

In [26]:
df_clean["ExperienceGroup"].value_counts()

ExperienceGroup
6-10 Years     607
11-20 Years    340
20+ Years      207
3-5 Years      193
0-2 Years      123
Name: count, dtype: int64

In [28]:
df_clean.shape

(1470, 37)

In [29]:
df_clean.columns.tolist()

['Age',
 'Attrition',
 'BusinessTravel',
 'DailyRate',
 'Department',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EmployeeID',
 'EnvironmentSatisfaction',
 'Gender',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager',
 'AttritionFlag',
 'TenureGroup',
 'AgeGroup',
 'YearsSincePromotionRatio',
 'ExperienceGroup']

In [30]:
df_clean.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeID                  0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
AttritionFlag               0
TenureGroup                 0
AgeGroup                    0
YearsSincePromotionRatio    0
ExperienceGroup             0
dtype: int64

In [31]:
df_clean["AttritionFlag"].value_counts()

AttritionFlag
0    1233
1     237
Name: count, dtype: int64

In [32]:
df_clean.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeID,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,AttritionFlag,TenureGroup,AgeGroup,YearsSincePromotionRatio,ExperienceGroup
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Yes,11,3,1,0,8,0,1,6,4,0,5,1,6-10 Years,36-45,0.000,6-10 Years
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,No,23,4,4,1,10,3,3,10,7,1,7,0,6-10 Years,46-55,0.100,6-10 Years
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Yes,15,3,2,0,7,3,3,0,0,0,0,1,0-2 Years,36-45,0.000,6-10 Years
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Yes,11,3,3,0,8,3,3,8,7,3,0,0,6-10 Years,25-35,0.375,6-10 Years
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,No,12,3,4,1,6,3,3,2,2,2,2,0,0-2 Years,25-35,1.000,6-10 Years

In [33]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeID                1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   object
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   object
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   object
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  OverTime                  1470 non-null   object
 21  PercentSalaryHike         1470 non-null   int64
 22  PerformanceRating         1470 non-null   int64
 23  RelationshipSatisfaction  1470 non-null   int64
 24  StockOptionLevel          1470 non-null   int64
 25  TotalWorkingYears         1470 non-null   int64
 26  TrainingTimesLastYear     1470 non-null   int64
 27  WorkLifeBalance           1470 non-null   int64
 28  YearsAtCompany            1470 non-null   int64
 29  YearsInCurrentRole        1470 non-null   int64
 30  YearsSinceLastPromotion   1470 non-null   int64
 31  YearsWithCurrManager      1470 non-null   int64
 32  AttritionFlag             1470 non-null   int64
 33  TenureGroup               1470 non-null   category
 34  AgeGroup                  1470 non-null   category
 35  YearsSincePromotionRatio  1470 non-null   float64
 36  ExperienceGroup           1470 non-null   category
dtypes: category(3), float64(1), int64(25), object(8)
memory usage: 395.5+ KB

In [34]:
import os

os.makedirs("../data/processed", exist_ok=True)

processed_path = "../data/processed/workforce_processed.csv"

df_clean.to_csv(
    processed_path,
    index=False
)

print("Processed dataset saved to:", processed_path)

Processed dataset saved to: ../data/processed/workforce_processed.csv